version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install .
      - pip install -r requirements.txt
      - rm -rf dspt
      - mkdir test-reports
  build:
    commands:
      
  post_build:
    commands:
      - echo Build completed on `date`

